"""Import public historical flight details from a private Flighty CSV.

python scripts/import-flighty.py /path/FlightyExport.csv --before YYYY-MM-DD
The CSV stays outside the repository. The cutoff excludes that date and later.
"""
import argparse
import csv
import datetime as dt
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AIRLINES = {
    'AAL': ('American Airlines', 'AA'), 'DAL': ('Delta Air Lines', 'DL'),
    'NKS': ('Spirit Airlines', 'NK'), 'SWA': ('Southwest Airlines', 'WN'),
    'UAL': ('United Airlines', 'UA'), 'BAW': ('British Airways', 'BA'),
    'ASA': ('Alaska Airlines', 'AS'), 'AVA': ('Avianca', 'AV'),
    'RPB': ('Aero Republica', 'P5'), 'FFT': ('Frontier Airlines', 'F9'),
    'SAS': ('Scandinavian Airlines', 'SK'), 'KLM': ('KLM', 'KL'),
    'ARG': ('Aerolíneas Argentinas', 'AR'), 'SWR': ('Swiss International Air Lines', 'LX'),
}
REQUIRED = {'Date', 'Airline', 'Flight', 'From', 'To', 'Canceled', 'Diverted To', 'Aircraft Type Name'}


def read_flights(path, airports, before):
    with path.open(newline='', encoding='utf-8-sig') as stream:
        reader = csv.DictReader(stream)
        if not REQUIRED.issubset(reader.fieldnames or []):
            raise ValueError('Not a supported Flighty export: required columns are missing')
        rows = list(reader)
    flights = []
    seen = set()
    audit = dict(source='Flighty', before=before.isoformat(), sourceRows=len(rows), canceled=0, cutoffExcluded=0, duplicates=0, diversions=0, timingUnavailable=0)
    for row in rows:
        flag = row['Canceled'].strip().lower()
        if flag not in ('true', 'false'):
            raise ValueError('Unrecognized cancellation flag')
        if flag == 'true':
            audit['canceled'] += 1
            continue
        day = dt.date.fromisoformat(row['Date'].strip())
        if day >= before:
            audit['cutoffExcluded'] += 1
            continue
        carrier = row['Airline'].strip()
        if carrier not in AIRLINES:
            raise ValueError(f'Airline lookup needed for {carrier}')
        airline, prefix = AIRLINES[carrier]
        origin = row['From'].strip()
        scheduled = row['To'].strip()
        destination = row['Diverted To'].strip() or scheduled
        for code in (origin, scheduled, destination):
            if code not in airports:
                raise ValueError(f'Airport lookup needed for {code}')
        identity = '|'.join([day.isoformat(), carrier, row['Flight'].strip(), origin, scheduled, row.get('Gate Departure (Scheduled)', '').strip()])
        if identity in seen:
            audit['duplicates'] += 1
            continue
        seen.add(identity)
        # Explicit allowlist: no Flighty IDs, booking references, seats, gates,
        # tail numbers, notes or exact departure/arrival timestamps are exported.
        flight = dict(id='flight-' + hashlib.sha256(identity.encode()).hexdigest()[:12], date=day.isoformat(), from_=origin, to=destination, airline=airline, flightNumber=prefix + row['Flight'].strip())
        if row['Aircraft Type Name'].strip():
            flight['aircraft'] = row['Aircraft Type Name'].strip()
        if destination != scheduled:
            flight['scheduledTo'] = scheduled
            audit['diversions'] += 1
        if not row.get('Landing (Actual)', '').strip() and not row.get('Gate Arrival (Actual)', '').strip():
            audit['timingUnavailable'] += 1
        flights.append(flight)
    # Flighty's row order is retained for same-date records.
    flights.sort(key=lambda f: f['date'], reverse=True)
    audit['included'] = len(flights)
    assert audit['included'] + audit['canceled'] + audit['cutoffExcluded'] + audit['duplicates'] == audit['sourceRows']
    return flights, audit


def render(flights, airports, audit):
    used = sorted({f[key] for f in flights for key in ('from_', 'to', 'scheduledTo') if key in f})
    text = "import type { LogAirport, PersonalFlight } from '@/lib/personal-flight-log';\n\n"
    text += '// Generated by scripts/import-flighty.py. The private CSV is not included.\n'
    text += 'const airports: Record<string, LogAirport> = ' + json.dumps({code: airports[code] for code in used}, ensure_ascii=False, indent=2) + ';\n\n'
    text += 'export const flightLogImport = ' + json.dumps(audit, indent=2) + ';\n\n'
    text += 'export const personalFlights: PersonalFlight[] = [\n'
    for flight in flights:
        fields = []
        for key, value in flight.items():
            if key in ('from_', 'to', 'scheduledTo'):
                fields.append(('from' if key == 'from_' else key) + ': airports[' + json.dumps(value) + ']')
            else:
                fields.append(key + ': ' + json.dumps(value, ensure_ascii=False))
        text += '  { ' + ', '.join(fields) + ' },\n'
    return text + '];\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('csv', type=Path)
    parser.add_argument('--before', type=dt.date.fromisoformat, required=True)
    parser.add_argument('--output', type=Path, default=ROOT / 'app/personal-flights.ts')
    args = parser.parse_args()
    airports = json.loads((ROOT / 'scripts/data/flight-log-airports.json').read_text())
    flights, audit = read_flights(args.csv, airports, args.before)
    args.output.write_text(render(flights, airports, audit))
    print(json.dumps(audit))


if __name__ == '__main__':
    main()
